using System;

namespace System.Xml.Serialization
{
	/// <summary>Signifies that the code was generated by the serialization infrastructure and can be reused for increased performance, when this attribute is applied to an assembly.</summary>
	[AttributeUsage(AttributeTargets.Assembly)]
	public sealed class XmlSerializerVersionAttribute : Attribute
	{
		private string _namespace;

		private string _parentAssemblyId;

		private Type _type;

		private string _version;

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class. </summary>
		public XmlSerializerVersionAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class for the specified type.</summary>
		/// <param name="type">The type that is being serialized.</param>
		public XmlSerializerVersionAttribute(Type type)
		{
			this._type = type;
		}

		/// <summary>Gets or sets the common language runtime (CLR) namespace of the assembly.</summary>
		/// <returns>A <see cref="T:System.String" /> containing the common language runtime (CLR) namespace of the assembly.</returns>
		public string Namespace
		{
			get
			{
				return this._namespace;
			}
			set
			{
				this._namespace = value;
			}
		}

		/// <summary>Gets or sets the identity of the parent assembly.</summary>
		/// <returns>The version of the parent assembly.</returns>
		public string ParentAssemblyId
		{
			get
			{
				return this._parentAssemblyId;
			}
			set
			{
				this._parentAssemblyId = value;
			}
		}

		/// <summary>Gets or sets the type that the serializer operates on.</summary>
		/// <returns>The <see cref="T:System.Type" /> to be serialized.</returns>
		public Type Type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}

		/// <summary>Gets or sets the assembly's version number.</summary>
		/// <returns>The version of the assembly.</returns>
		public string Version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
	}
}
