using System;

namespace Neptune.Setting
{
	public enum SettingViewAction : byte
	{
		ACTION_SETTINGS,
		ACTION_APN_SETTINGS,
		ACTION_LOCATION_SOURCE_SETTINGS,
		ACTION_WIRELESS_SETTINGS,
		ACTION_WIFI_SETTINGS,
		ACTION_AIRPLANE_MODE_SETTINGS,
		ACTION_BLUETOOTH_SETTINGS,
		ACTION_DATE_SETTINGS,
		ACTION_DEVICE_INFO_SETTINGS,
		ACTION_DISPLAY_SETTINGS,
		ACTION_INTERNAL_STORAGE_SETTINGS
	}
}
