using System;

namespace System.CodeDom.Compiler
{
	/// <summary>Identifies code generated by a tool. This class cannot be inherited.</summary>
	[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
	public sealed class GeneratedCodeAttribute : Attribute
	{
		private string tool;

		private string version;

		/// <summary>Initializes a new instance of the <see cref="T:System.CodeDom.Compiler.GeneratedCodeAttribute" /> class specifying the name and version of the tool that generated the code.</summary>
		/// <param name="tool">The name of the tool that generated the code.</param>
		/// <param name="version">The version of the tool that generated the code.</param>
		public GeneratedCodeAttribute(string tool, string version)
		{
			this.tool = tool;
			this.version = version;
		}

		/// <summary>Gets the name of the tool that generated the code.</summary>
		/// <returns>The name of the tool that generated to code.</returns>
		public string Tool
		{
			get
			{
				return this.tool;
			}
		}

		/// <summary>Gets the version of the tool that generated the code.</summary>
		/// <returns>The version of the tool that generated the code.</returns>
		public string Version
		{
			get
			{
				return this.version;
			}
		}
	}
}
