using System;

namespace MissionData
{
	public class Type
	{
		public enum Mission
		{
			NotComp,
			NotRecieved,
			Recieved,
			NotComp_Jump
		}

		public enum Category
		{
			QUEST = 1,
			MEAT,
			GASHA,
			MEAL,
			REINFORCE,
			EVOLUTION,
			SUCCESSION,
			LABORATORY,
			ALL_CLEAR = 101,
			FRIEND = 201,
			COLOSSEUM = 204,
			BEGINNER_AROUSAL = 9,
			BEGINNER_QUEST_CLEAR_AREA2 = 110,
			BEGINNER_QUEST_CLEAR_AREA3,
			BEGINNER_QUEST_CLEAR_AREA5,
			BEGINNER_QUEST_CLEAR_AREA7,
			BEGINNER_QUEST_CLEAR_DAY_EASY,
			BEGINNER_QUEST_CLEAR_DAY_NORMAL,
			BEGINNER_QUEST_CLEAR_DAY_HARD,
			BEGINNER_QUEST_CLEAR_DESCENT_EASY,
			BEGINNER_QUEST_CLEAR_DESCENT_NORMAL,
			BEGINNER_QUEST_CLEAR_DESCENT_HARD,
			BEGINNER_FACILITY_LEV_MEATFARM = 131,
			BEGINNER_FACILITY_LEV_STOREHOUSE,
			BEGINNER_FACILITY_LEV_RESTAURANT,
			BEGINNER_FACILITY_LEV_TRAINING,
			BEGINNER_LEVMAX_GROWSTEP_GROWING = 144,
			BEGINNER_LEVMAX_GROWSTEP_RIPE,
			BEGINNER_LEVMAX_GROWSTEP_PERFECT,
			BEGINNER_EVOLVE_GROWSTEP_GROWING = 154,
			BEGINNER_EVOLVE_GROWSTEP_RIPE,
			BEGINNER_EVOLVE_GROWSTEP_PERFECT,
			BEGINNER_MISSION_LEV = 191
		}
	}
}
