using System;

namespace MissionData
{
	public class Type
	{
		public enum Mission
		{
			NotComp,
			NotRecieved,
			Recieved,
			NotComp_Jump
		}

		public enum Category
		{
			QUEST = 1,
			BEGINNER_QUEST_CLEAR_AREA2 = 110,
			BEGINNER_QUEST_CLEAR_AREA3,
			BEGINNER_QUEST_CLEAR_AREA5,
			BEGINNER_QUEST_CLEAR_AREA7,
			BEGINNER_QUEST_CLEAR_AREA10 = 125,
			BEGINNER_QUEST_CLEAR_AREA14,
			BEGINNER_QUEST_CLEAR_AREA19,
			BEGINNER_QUEST_CLEAR_AREA_ALL = 120,
			BEGINNER_QUEST_CLEAR_DAY_EASY = 114,
			BEGINNER_QUEST_CLEAR_DAY_NORMAL,
			BEGINNER_QUEST_CLEAR_DAY_HARD,
			BEGINNER_QUEST_CLEAR_BEGINNER_DESCENT_EASY,
			BEGINNER_QUEST_CLEAR_BEGINNER_DESCENT_NORMAL,
			BEGINNER_QUEST_CLEAR_BEGINNER_DESCENT_HARD,
			BEGINNER_QUEST_CLEAR_DESCENT_EASY = 121,
			BEGINNER_QUEST_CLEAR_DESCENT_NORMAL,
			BEGINNER_QUEST_CLEAR_DESCENT_HARD,
			BEGINNER_FRIENDSHIP_POINT_90 = 161,
			BEGINNER_FRIENDSHIP_POINT_150,
			BEGINNER_FRIENDSHIP_POINT_210,
			BEGINNER_FRIENDSHIP_POINT_300,
			MEAT = 2,
			BEGINNER_FACILITY_LEV_MEATFARM = 131,
			BEGINNER_FACILITY_LEV_STOREHOUSE,
			BEGINNER_FACILITY_LEV_RESTAURANT,
			BEGINNER_FACILITY_LEV_TRAINING,
			MEAL = 4,
			BEGINNER_LEVMAX_GROWSTEP_GROWING = 144,
			BEGINNER_LEVMAX_GROWSTEP_RIPE,
			BEGINNER_LEVMAX_GROWSTEP_PERFECT,
			BEGINNER_LEVMAX_GROWSTEP_ULTIMATE,
			EVOLUTION = 6,
			BEGINNER_EVOLVE_GROWSTEP_GROWING = 154,
			BEGINNER_EVOLVE_GROWSTEP_RIPE,
			BEGINNER_EVOLVE_GROWSTEP_PERFECT,
			BEGINNER_OBTAIN_ULTIMATE_MONSTER = 181,
			GASHA = 3,
			REINFORCE = 5,
			SUCCESSION = 7,
			LABORATORY,
			BEGINNER_AWAKEN = 10,
			BEGINNER_AROUSAL = 9,
			FRIEND = 201,
			COLOSSEUM = 204,
			COLOSSEUM_ONCE,
			ALL_CLEAR = 101,
			BEGINNER_MISSION_LEV = 191,
			MIDRANGE_MISSION_LEV
		}

		public enum DisplayGroup
		{
			beginner = 3,
			midrange,
			daily = 1,
			total
		}
	}
}
