using System;

public enum LeaderSkillType
{
	HpFollowingDamageUp = 1,
	HpFollowingAttackUp,
	HpFollowingDefenceUp,
	HpFollowingSpecialAttackUp,
	HpFollowingSpecialDefenceUp,
	HpFollowingSpeedUp,
	HpFollowingHitRateUp,
	HpFollowingSatisfactionRateUp,
	HpMaxDamageUp,
	HpMaxAttackUp,
	HpMaxDefenceUp,
	HpMaxSpecialAttackUp,
	HpMaxSpecialDefenceUp,
	HpMaxSpeedUp,
	HpMaxHitRateUp,
	HpMaxMachSatisfactionRateUp,
	SpeciesMachDamageUp,
	SpeciesMachHpUp,
	SpeciesMachAttackUp,
	SpeciesMachDefenceUp,
	SpeciesMachSpecialAttackUp,
	SpeciesMachSpecialDefenceUp,
	SpeciesMachSpeedUp,
	SpeciesMachHitRateUp,
	SpeciesMachSatisfactionRateUp,
	DamageUp,
	HpUp,
	AttackUp,
	DefenceUp,
	SpecialAttackUp,
	SpecialDefenceUp,
	SpeedUp,
	HitRateUp,
	SatisfactionRateUp,
	ToleranceUp
}
