using System;

namespace Neptune.OAuth
{
	public enum VenusStatusE
	{
		NONE,
		RESPONSE_SUCCESS,
		RESPONSE_ERROR,
		RESPONSE_MAINTENANCE,
		RESPONSE_PULTIPLE,
		RESPONSE_OLDVERSION,
		RESPONSE_SERVER_LOAD_HIGH,
		RESPONSE_APPLICATION_ERROR,
		RESPONSE_CSRF_ERROR,
		RESPONSE_NOT_ENOUGH_BP_ERROR,
		RESPONSE_NOT_ENOUGH_AP_ERROR,
		RESPONSE_PENALTY,
		RESPONSE_TIMESTAMP
	}
}
